name: Deploy

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: lint

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Mock E2E Test
        run: echo "Running mock end-to-end tests... testing complete"

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, e2e]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Mock deploy
        run: echo "Running mock deployment... deployment complete"
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/amd64,linux/arm64/v8
      #     push: true
      #     target: prod
      #     tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
